spring:
    datasource:
        url: tardydb.cprkwuh7mclf.ap-northeast-2.rds.amazonaws.com
        driverClassName: org.mariadb.jdbc.Driver
        username: tardydb
        password: tardygramdb
    jpa:
        hibernate:
            ddl-auto: create
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
server:
    port: 9000
logging:
  level:
    org.springframework.security: debug 
